name: "Build Paraview"
description: "Build paraview"
outputs:
  build-directory: 
    description: "Path of Paraview build directory"
    value: ${{ steps.build.outputs.build-dir }}
runs:
  using: "composite"
  steps:
    - name: "Paraview dependencies Linux"
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get install git cmake build-essential libgl1-mesa-dev libxt-dev libqt5x11extras5-dev libqt5help5 qttools5-dev qtxmlpatterns5-dev-tools libqt5svg5-dev python3-dev python3-numpy libopenmpi-dev libtbb-dev ninja-build qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

    - name: "Paraview dependencies macOS"
      if: ${{ runer.os == 'macOS' }}
      shell: bash
      run: |
        brew install open-mpi cmake mesa tbb ninja gdal qt5
   
    - name: "Build"
      id: "build"
      shell: bash
      working-directory: ${{ runner.workspace }}
      run: |
        git clone --recursive https://gitlab.kitware.com/paraview/paraview.git
        
        
        cmake -E make_directory ${{ runner.workspace }}/paraview/build
        cmake -E chdir ${{ runner.workspace }}/paraview/build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --parallel $(nproc)
      
        echo "build-dir=${{ runner.workspace }}/paraview/build" >> "$GITHUB_OUTPUT"

        cmake -E chdir ${{ runner.workspace }}


