name: "Build Paraview"
description: "Build paraview"
outputs:
  build-dir: 
    description: "Path of Paraview build directory"
    value: ${{ runner.workspace }}/paraview/build

runs:
  using: "composite"
  steps:
    - name: "Paraview dependencies Linux"
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get install git cmake build-essential libgl1-mesa-dev libxt-dev libqt5x11extras5-dev libqt5help5 qttools5-dev qtxmlpatterns5-dev-tools libqt5svg5-dev python3-dev python3-numpy libopenmpi-dev libtbb-dev ninja-build qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

    - name: "Paraview dependencies macOS"
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        brew install open-mpi cmake mesa tbb ninja gdal qt5

        echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.bashrc
        echo 'export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"' >> ~/.bashrc
        echo 'export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"' >> ~/.bashrc

        cat ~/.bashrc

    - name: "Build cache"
      id: build-cache
      uses: actions/cache@v4
      with:
        save-always: true
        path: ${{ runner.workspace }}/paraview
        key: ${{ runner.os }}-paraviewbuild

    - name: "Clone"
      if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ${{ runner.workspace }}
      run: |
        git clone -b v5.13.3 --depth 1 --recursive https://gitlab.kitware.com/paraview/paraview.git

        cmake -E make_directory ${{ runner.workspace }}/paraview/build -DCMAKE_POSITION_INDEPENDENT_CODE=ON

    - name: "Build"
      if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      id: build
      shell: bash
      working-directory: ${{ runner.workspace }}/paraview/build
      run: |
        source ~/.bashrc
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . 


