name: "Build DGtal"
description: "Builds the DGtal library"
inputs:
  config:
    desciption: "Config name"
    required: true
    default: "Default"

outputs:
  build-dir:
    description: "DGtal build directory"
    value: ${{ runner.workspace }}/DGtal/build 

runs:
  using: "composite"
  steps:
    - name: "DGtal dependencies and setup"
      uses: BDoignies/DGtal/.github/actions/setup-os@CIfix

    - name: "Cloning DGtal"
      if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      working-directory: ${{ runner.workspace }}
      shell: bash
      run: |
        git clone -b main2.0 --depth 1 https://github.com/DGtal-team/DGtal.git

    - name: "Build cache"
      id: build-cache
      uses: actions/cache@v4
      with:
        path: ${{ runner.workspace }}/DGtal
        key: ${{ runner.os }}-dgtalbuild-${{ inputs.config }}

    - name: "DGtal config"
      if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      uses: BDoignies/DGtal/.github/actions/dgtal-config@CIfix
      with:
        dgtal: ${{ runner.workspace }}/DGtal
        config-name: ${{ inputs.config }}

    - name: "Building DGtal"
      id: build
      if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      uses: BDoignies/DGtal/.github/actions/cmake@CIfix
      with:
        test: false
        dgtal: ${{ runner.workspace }}/DGtal
        build-dir: ${{ runner.workspace }}/DGtal/build
        build-config: ${{ steps.config.ouputs.cmake-config }}

