name: "Build DGtal"
description: "Builds the DGtal library"
inputs:
  config:
    desciption: "Config name"
    required: true
    default: "Default"

outputs:
  build-dir:
    description: "DGtal build directory"
    value: ${{ steps.build.outputs.build-dir }}

runs:
  using: "composite"
  steps:
    - name: "Cloning DGtal"
      working-directory: ${{ runner.workspace }}
      shell: bash
      run: |
        git clone -b main2.0 --depth 1 https://github.com/DGtal-team/DGtal.git

    - name: "DGtal config"
      uses: BDoignies/DGtal/.github/actions/dgtal-config@CIfix
      with:
        dgtal: ${{ runner.workspace }}/DGtal
        config-name: "Default"

    - name: "DGtal dependencies and setup"
      uses: BDoignies/DGtal/.github/actions/setup-os@CIfix

    - name: "Building DGtal"
      id: "build"
      uses: BDoignies/DGtal/.github/actions/cmake@CIfix
      with:
        test: false
        dgtal: ${{ runner.workspace }}/DGtal
        build-dir: ${{ runner.workspace }}/DGtal/build
        build-config: ${{ steps.config.ouputs.cmake-config }}

