name: CI (linux/macOS/windows)

on:
  push:
    branches: [CI, main]
  pull_request:
    branches: [CI, main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build DGtal
        id: dgtal
        uses: ./.github/actions/dgtal
      
      - name: Build paraview
        id: paraview
        uses: ./.github/actions/paraview

      - name: Build folder
        run: cmake -E make_directory ${{ runner.workspace }}/DGtal-paraview/build

#      - name: Building plugin
#        shell: bash
#        working-directory: ${{ runner.workspace }}/DGtal-paraview/build
#        run: |
#          echo "cmake .. -DParaView_DIR=${{ steps.paraview.outputs.build-dir }} -DDGtal_DIR=${{ steps.dgtal.outputs.build-dir }}"
#          cmake .. -DParaView_DIR=${{ steps.paraview.outputs.build-dir }} -DDGtal_DIR=${{ steps.dgtal.outputs.build-dir }}
#          cmake --build .
#
